### PR TITLE
Feature/mint updates

### PR DESCRIPTION
**Pull request by StephenSeltzer**
Contains a variety of updates. Some directed at making workstation work better on Mint and some general improvements. Also updated versions where appropriate.

### CODE REVIEW

**Comment by smoyer64** [comment]
How does removing the Path elements in the desktop files affect running those applications on Ubuntu?

**Comment by StephenSeltzer** [comment]
To be honest, I didn't try it on Ubuntu but I doubt that it would cause an issue.

**Comment by smoyer64** [comment]
I think I've got a memory stick with 16.04 on it at work ... we can try it out on a "LiveCD".  Why does Mint object to these parameters?

**Comment by StephenSeltzer** [comment]
I'm not sure. It simply doesn't open the application. As soon as I removed
the ~ the application opened with no problem.

**Comment by smoyer64** [comment]
IIRC, those were added because on Ubuntu that parameter specified where the data directory would be written.

**Comment by StephenSeltzer** [comment]
I did some researching on the path entry. I found it listed in the spec but in practice found no examples that actually use it. It is listed as an optional parameter and falls back to the user's home directory as default. I was able to get path to be accepted but only if I gave it an explicit path such as "/home/sgs116/". It would not accept "~".

**Comment by StephenSeltzer** [comment]
Updated dbeaver to version 4.3.4

**Comment by smoyer64** [comment]
I'm going to merge this simple to keep you from adding any more commits ... Usually Github projects benefit from meritocratic behavior but I guess persistence can be useful too.

**Pull request merged**
